#!/usr/bin/env bash
# =============================================================================
# dream_cycle.sh
# -----------------------------------------------------------------------------
# Jarvis DREAM CYCLE — overnight memory consolidation cron job.
# Runs: consolidate episodic → crystallized, prune decayed entries,
# detect contradictions, surface patterns, generate morning pulse.
# =============================================================================
set -euo pipefail

VENV="/home/arif/.hermes/hermes-agent/venv/bin/python"
MEMORY_SCRIPT="$HOME/.hermes/scripts/temporal_tiered_memory.py"
REPORT_FILE="$HOME/.hermes/memory/dream_cycle_report.md"
TS=$(date +%Y-%m-%dT%H:%M:%S%z)

{
  echo "# Dream Cycle Report — $TS"
  echo ""

  echo "## 1. Memory Stats (before)"
  echo '```'
  "$VENV" "$MEMORY_SCRIPT" stats 2>&1
  echo '```'
  echo ""

  echo "## 2. Consolidation (pattern detection)"
  echo '```'
  "$VENV" "$MEMORY_SCRIPT" consolidate --min-sessions 2 2>&1
  echo '```'
  echo ""

  echo "## 3. Decay Status"
  echo '```'
  STATS=$("$VENV" "$MEMORY_SCRIPT" stats 2>&1)
  DECAYED=$(echo "$STATS" | python3 -c "import json,sys; print(json.load(sys.stdin).get('decayed_below_10pct',0))" 2>/dev/null || echo "?")
  echo "Entries below 10% weight: $DECAYED"
  echo '```'
  echo ""

  echo "## 4. Memory Stats (after)"
  echo '```'
  "$VENV" "$MEMORY_SCRIPT" stats 2>&1
  echo '```'
  echo ""

  echo "## 5. Top Insights (recent)"
  echo '```'
  "$VENV" "$MEMORY_SCRIPT" retrieve --type-filter insight --top 3 2>&1 | python3 -c "
import sys, json
for line in sys.stdin:
    if line.strip():
        d=json.loads(line)
        print(f\"  [{d.get('content_type','?')}] {d.get('text','')[:150]}\")
" 2>/dev/null || echo "  (no insights yet)"
  echo '```'
  echo ""

  echo "---"
  echo "_Auto-generated by Jarvis Dream Cycle. Next run: tomorrow._"
} > "$REPORT_FILE"

echo "Dream cycle complete. Report: $REPORT_FILE"
